// SPDX-License-Identifier: Apache-2.0
// Copyright 2024 The TensorFlow Authors. All Rights Reserved.
// Copyright 2026 Hematite Contributors.
//
// This file contains golden reference output values for TFLite Micro operator
// verification. Generated by tools/generate_goldens.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// ═══════════════════════════════════════════════════════════════════════════════
// WARNING: TOOL-INTERNAL REFERENCE VALUES — NOT CAPTURED FROM EXECUTED TFLM
//
// The values in this file were generated by a scalar reimplementation of the
// TFLite Micro int8 reference kernels, NOT by capturing output from an
// executed TFLM binary. They are faithful to the TFLM arithmetic specification
// (i32 accumulate, MultiplyByQuantizedMultiplier with saturating rounding
// doubling high-mul, per-channel requantize, saturating cast, zero-point
// offset handling, fused-activation clamping) but have NOT been cross-validated
// against a running TFLM interpreter.
//
// T5.0 MUST re-generate the golden corpus against a real executed TFLM build
// at the pinned SHA before any public bit-exactness claim is made, or before
// any Phase 5 benchmarking conclusions are drawn.
//
// This provenance note is non-negotiable and must be removed ONLY by T5.0
// after real-TFLM regeneration.
// ═══════════════════════════════════════════════════════════════════════════════

// GRU PROVENANCE: TFLM has NO GRU kernel at the pinned SHA.
// These goldens were generated with hand-rolled fixed-point gate math
// (gemmlowp logistic/tanh via exp_on_negative_values) and verified via
// manual bit-level self-check assertions (sigmoid(0)=0.5, tanh(0)=0,
// endpoint saturation, monotonicity). No reference implementation exists.
// See tools/generate_goldens/README.md for full provenance.

pub const GOLDEN_TFLM_VERSION: &str = "18b9e6f2a8c5a9518e588f59c2ba16ef7ef9d551";
pub const GOLDEN_PROVENANCE: &str = "hand-rolled-gemmlowp-fixed-point; NO TFLM GRU kernel exists; see README";

pub const INPUT_SHAPE: [i32; 4] = [1, 2, 1, 2];
pub const FILTER_SHAPE: [i32; 4] = [0, 0, 0, 0];
pub const OUTPUT_SHAPE: [i32; 4] = [1, 2, 1, 2];

pub const NUM_UNITS: i32 = 2;
pub const INPUT_SIZE: i32 = 2;
pub const NUM_TIMESTEPS: i32 = 2;

pub const INPUT_OFFSET: i32 = 0;
pub const OUTPUT_OFFSET: i32 = 0;
pub const OUTPUT_ACTIVATION_MIN: i32 = -128;
pub const OUTPUT_ACTIVATION_MAX: i32 = 127;

pub const INPUT_DATA: [i8; 4] = [
    -20, 10, 15, -5,
];

pub const WEIGHTS_DATA: [i8; 12] = [
    2, -3, 1, 4, 1, 2, -2, 1, 3, -1, -1, 2,
];

pub const RECURRENT_WEIGHTS_DATA: [i8; 12] = [
    1, -2, 3, 1, -1, 2, 1, -3, 2, 1, -2, 3,
];

pub const BIAS_DATA: [i32; 6] = [
    5, -5, 10, -10, -5, 5,
];

pub const OUTPUT_MULTIPLIER: [i32; 1] = [
    1073741824,
];

pub const OUTPUT_SHIFT: [i32; 1] = [
    -3,
];

pub const EXPECTED_OUTPUT: [i8; 4] = [
    -49, 27, -84, 95,
];

pub const INIT_HIDDEN_STATE: [i16; 2] = [
    0, 0,
];

