// SPDX-License-Identifier: Apache-2.0
// Copyright 2024 The TensorFlow Authors. All Rights Reserved.
// Copyright 2026 Hematite Contributors.
//
// This file contains golden reference output values for TFLite Micro operator
// verification. Generated by tools/generate_goldens.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// ═══════════════════════════════════════════════════════════════
// CAPTURED FROM EXECUTED TFLITE-MICRO — HARD_SWISH OP (RE-TIERED T10)
//
// Previously DOWNGRADED (integer-div-rational-approx, NOT
// TFLM-faithful). Now re-tiered: INPUT_DATA was run through the
// HardSwish micro-model tools/tflm-goldens/models/hard_swish_int8.tflite
// (int8, input scale 1.0 / zero-point 0, output scale 1.0 /
// zero-point 0) via the EXECUTED tflite-micro reference HardSwish
// kernel (HardSwishParams chain: SaturatingDoublingHighMul /
// SaturatingRoundingDoublingHighMul / RoundingDivideByPOT, see
// tensorflow/lite/kernels/internal/reference/hard_swish.h at the
// pinned SHA). EXPECTED_OUTPUT is the exact int8 output captured
// from that execution (VERBATIM).
// ═══════════════════════════════════════════════════════════════

/// TFLite Micro pin that defines this golden corpus.
pub const GOLDEN_TFLM_VERSION: &str = "18b9e6f2a8c5a9518e588f59c2ba16ef7ef9d551";

/// Executed interpreter that produced these values.
pub const GOLDEN_RUNTIME_VERSION: &str = "tflite-micro @ 18b9e6f2a8c5a9518e588f59c2ba16ef7ef9d551 (executed, reference kernels)";

/// Provenance: captured from executed tflite-micro at the pinned
/// SHA via the tools/tflm-goldens host harness (hard_swish
/// micro-model case).
pub const GOLDEN_PROVENANCE: &str = "captured-from-executed-tflite-micro @ 18b9e6f2a8c5a9518e588f59c2ba16ef7ef9d551; hard_swish micro-model; date 2026-08-10; cmd: (cd tools/tflm-goldens && make TFLM_ROOT=/tmp/tflite-micro run > generated/harness_output.txt)";

pub const INPUT_SHAPE: [i32; 4] = [1, 1, 1, 8];
pub const OUTPUT_SHAPE: [i32; 4] = [1, 1, 1, 8];

pub const INPUT_ZERO_POINT: i32 = 0;
pub const OUTPUT_ZERO_POINT: i32 = 0;

pub const INPUT_SCALE: f64 = 1.0;
pub const OUTPUT_SCALE: f64 = 1.0;

// HardSwish: x * ReLU6(x+3) / 6 (executed TFLM HardSwishParams chain)

pub const INPUT_DATA: [i8; 8] = [
    -10, -5, -3, -1, 0, 3, 6, 10,
];

pub const EXPECTED_OUTPUT: [i8; 8] = [
    0, 0, 0, 0, 0, 3, 6, 10,
];

