// SPDX-License-Identifier: Apache-2.0
// Copyright 2024 The TensorFlow Authors. All Rights Reserved.
// Copyright 2026 Hematite Contributors.
//
// This file contains golden reference output values for TFLite Micro operator
// verification. Generated by tools/generate_goldens.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// ═══════════════════════════════════════════════════════════════════════════════
// WARNING: TOOL-INTERNAL REFERENCE VALUES — NOT CAPTURED FROM EXECUTED TFLM
//
// The values in this file were generated by a scalar reimplementation of the
// TFLite Micro int8 reference kernels, NOT by capturing output from an
// executed TFLM binary. They are faithful to the TFLM arithmetic specification
// (i32 accumulate, MultiplyByQuantizedMultiplier with saturating rounding
// doubling high-mul, per-channel requantize, saturating cast, zero-point
// offset handling, fused-activation clamping) but have NOT been cross-validated
// against a running TFLM interpreter.
//
// T5.0 MUST re-generate the golden corpus against a real executed TFLM build
// at the pinned SHA before any public bit-exactness claim is made, or before
// any Phase 5 benchmarking conclusions are drawn.
//
// This provenance note is non-negotiable and must be removed ONLY by T5.0
// after real-TFLM regeneration.
// ═══════════════════════════════════════════════════════════════════════════════

/// TFLite Micro pin that defines this golden corpus.
pub const GOLDEN_TFLM_VERSION: &str = "18b9e6f2a8c5a9518e588f59c2ba16ef7ef9d551";

/// Provenance of these golden values.
pub const GOLDEN_PROVENANCE: &str = "tool-internal-reference-reimplementation; NOT captured from executed TFLM; see tools/generate_goldens/README.md";

pub const INPUT_SHAPE: [i32; 4] = [1, 2, 3, 1];
pub const OUTPUT_SHAPE: [i32; 4] = [1, 1, 3, 1];

pub const AXIS_0: i32 = 1;
pub const AXIS_COUNT: i32 = 1;

// ReduceMax: max of elements along axis 1 (pure int8 comparison, no requantize)
pub const INPUT_DATA: [i8; 6] = [
    5, 1, 7, -3, 9, -2,
];

pub const EXPECTED_OUTPUT: [i8; 3] = [
    5, 9, 7,
];

