#!/usr/bin/env python3
"""Extract golden inputs into raw .bin files for the tflite-micro harness.

Single source of truth: the Rust golden files under
`hematite-tests/goldens/models/*.rs`. This script parses the `INPUT_DATA`
i8 arrays (plus INPUT_SHAPE / OUTPUT_SHAPE / EXPECTED_OUTPUT / MODEL_PATH)
and emits, for each of the 6 zoo models:

  generated/<stem>.bin      raw little-endian i8 input bytes (byte-identical
                            to the Rust array; this is THE critical constraint)
  generated/manifest.json   per-model: tflite path, shapes, element counts
  generated/cases.inc       C++ fragment consumed by main.cc (model table)
  generated/golden_hashes.json  FNV-1a (32-bit, seed 2166136261, prime
                            16777619, over output bytes i8->u8) of each
                            golden EXPECTED_OUTPUT, for the kws sanity gate
                            and future regeneration (todo T10) comparison

Deterministic and re-runnable: pure stdlib, stable ordering, no timestamps.

Usage:
    python3 extract_inputs.py [--goldens-dir ../../hematite-tests/goldens/models]
                              [--out-dir generated]
"""

import argparse
import json
import re
import sys
from pathlib import Path

# FNV-1a 32-bit, mirroring hematite-benchmarks/src/model_validation.rs::fnv1a
# (seed 2166136261, prime 16777619, over raw output bytes i8-as-u8).
FNV_OFFSET_BASIS = 2166136261
FNV_PRIME = 16777619


def fnv1a_i8(values: list[int]) -> int:
    h = FNV_OFFSET_BASIS
    for v in values:
        h ^= v & 0xFF
        h = (h * FNV_PRIME) & 0xFFFFFFFF
    return h


def parse_const(text: str, name: str) -> list[int] | None:
    """Parse `pub const NAME: [i8; N] = [ ... ];` into a list of ints."""
    m = re.search(rf"pub const {name}:\s*\[i8;\s*\d+\]\s*=\s*\[(.*?)\];", text, re.S)
    if not m:
        return None
    return [int(x.strip()) for x in m.group(1).split(",") if x.strip()]


def parse_shape(text: str, name: str) -> list[int] | None:
    m = re.search(rf"pub const {name}:\s*\[i32;\s*\d+\]\s*=\s*\[(.*?)\];", text, re.S)
    if not m:
        return None
    return [int(x.strip()) for x in m.group(1).split(",") if x.strip()]


def parse_str_const(text: str, name: str) -> str | None:
    m = re.search(rf'pub const {name}:\s*&str\s*=\s*"([^"]*)";', text)
    return m.group(1) if m else None


def prod(xs: list[int]) -> int:
    n = 1
    for x in xs:
        n *= x
    return n


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--goldens-dir", default="../../hematite-tests/goldens/models")
    ap.add_argument("--out-dir", default="generated")
    args = ap.parse_args()

    goldens_dir = Path(args.goldens_dir).resolve()
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    # Deterministic ordering: fixed, documented list (matches the plan's 6
    # zoo models). Each stem must exist in the goldens dir.
    stems = [
        "sine",
        "hello_world_int8",
        "kws_micro_speech_int8",
        "anomaly_detect_int8",
        "person_detect_int8",
        "mobilenet_v2_1.0_224_int8",
    ]

    manifest = []
    golden_hashes = {}
    cases_inc_lines = [
        "// GENERATED by extract_inputs.py — do not edit. Single source of",
        "// truth: hematite-tests/goldens/models/*.rs (INPUT_DATA arrays).",
        "struct ModelCase {",
        "  const char* name;",
        "  const char* tflite_path;",
        "  const char* input_bin_path;",
        "  size_t input_bytes;   // expected INPUT_DATA element count",
        "  size_t arena_bytes;   // tensor arena for this model",
        "};",
        "static const ModelCase kCases[] = {",
    ]

    # Arena sizes (host-side, generous; activations only — weights live in the
    # model file, not the arena). Bump only if AllocateTensors reports failure.
    arena = {
        "sine": 64 * 1024,
        "hello_world_int8": 64 * 1024,
        "kws_micro_speech_int8": 128 * 1024,
        "anomaly_detect_int8": 4 * 1024 * 1024,
        "person_detect_int8": 16 * 1024 * 1024,
        "mobilenet_v2_1.0_224_int8": 64 * 1024 * 1024,
    }

    for stem in stems:
        rs = goldens_dir / f"{stem}.rs"
        if not rs.exists():
            print(f"error: golden file not found: {rs}", file=sys.stderr)
            return 1
        text = rs.read_text()

        input_data = parse_const(text, "INPUT_DATA")
        expected = parse_const(text, "EXPECTED_OUTPUT")
        input_shape = parse_shape(text, "INPUT_SHAPE")
        output_shape = parse_shape(text, "OUTPUT_SHAPE")
        model_path = parse_str_const(text, "MODEL_PATH")
        if None in (input_data, expected, input_shape, output_shape, model_path):
            print(f"error: could not parse all consts from {rs}", file=sys.stderr)
            return 1

        if len(input_data) != prod(input_shape):
            print(
                f"error: {stem}: INPUT_DATA len {len(input_data)} != "
                f"prod(INPUT_SHAPE) {prod(input_shape)}",
                file=sys.stderr,
            )
            return 1
        if len(expected) != prod(output_shape):
            print(
                f"error: {stem}: EXPECTED_OUTPUT len {len(expected)} != "
                f"prod(OUTPUT_SHAPE) {prod(output_shape)}",
                file=sys.stderr,
            )
            return 1

        bin_path = out_dir / f"{stem}.bin"
        bin_path.write_bytes(bytes((v & 0xFF) for v in input_data))

        manifest.append(
            {
                "name": stem,
                "tflite_path": model_path,
                "input_shape": input_shape,
                "output_shape": output_shape,
                "input_len": len(input_data),
                "output_len": len(expected),
                "input_bin": f"{stem}.bin",
                "arena_bytes": arena[stem],
            }
        )
        golden_hashes[stem] = fnv1a_i8(expected)

        cases_inc_lines.append(
            # "../../" re-bases the workspace-relative golden MODEL_PATH onto
            # the harness dir (tools/tflm-goldens), which main.cc resolves at runtime.
            f'  {{"{stem}", "../../{model_path}", "generated/{stem}.bin", '
            f"{len(input_data)}, {arena[stem]}}},"
        )
        print(
            f"{stem}: input={input_shape} ({len(input_data)}B) "
            f"output={output_shape} ({len(expected)} elems) "
            f"golden_fnv1a=0x{golden_hashes[stem]:08x}"
        )

    cases_inc_lines.append("};")

    (out_dir / "manifest.json").write_text(
        json.dumps(manifest, indent=2) + "\n"
    )
    (out_dir / "cases.inc").write_text("\n".join(cases_inc_lines) + "\n")
    (out_dir / "golden_hashes.json").write_text(
        json.dumps(golden_hashes, indent=2, sort_keys=True) + "\n"
    )
    print(f"wrote {len(manifest)} inputs to {out_dir}/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
