// tflm-goldens — golden-capture harness for tflite-micro at pinned SHA.
//
// Loads each of the 6 zoo tflite models through the REAL tflite-micro
// interpreter (tflite::MicroInterpreter + reference kernels), runs inference
// on the byte-identical INPUT_DATA the Rust goldens use (from
// generated/<stem>.bin, produced by extract_inputs.py), and prints the output
// tensor as a comma-separated i8 array plus an FNV-1a 32-bit hash.
//
// This retires the provenance debt: the current model goldens were captured
// from ai-edge-litert (LiteRT, double-rounding) or the in-repo TFLM arithmetic
// reimplementation — NOT from executed tflite-micro. See README.md and
// models/zoo/DEFERRED_MODELS.md §6 for the divergence rationale.
//
// Host-only, single-threaded, deterministic. Reference kernels only
// (TF_LITE_DISABLE_X86_NEON is set by the build, matching the library).

#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <vector>

#include "tensorflow/lite/micro/micro_interpreter.h"
#include "tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "tensorflow/lite/schema/schema_generated.h"

// Generated by extract_inputs.py (single source of truth: the Rust goldens).
#include "cases.inc"

namespace {

// Directory of the harness binary (from argv[0]); all paths in cases.inc are
// relative to it, so the harness is runnable from any working directory.
std::string g_base_dir = ".";

std::string ResolvePath(const char* rel) { return g_base_dir + "/" + rel; }

std::string DirNameOf(const char* argv0) {
  const std::string s = argv0;
  const size_t slash = s.find_last_of('/');
  if (slash == std::string::npos) return ".";
  if (slash == 0) return "/";
  return s.substr(0, slash);
}

// FNV-1a 32-bit over raw output bytes (i8 -> u8), identical to
// hematite-benchmarks/src/model_validation.rs::fnv1a and
// hematite-tests' golden hashes.
uint32_t Fnv1a(const int8_t* data, size_t n) {
  uint32_t h = 2166136261u;
  for (size_t i = 0; i < n; ++i) {
    h ^= static_cast<uint8_t>(data[i]);
    h *= 16777619u;
  }
  return h;
}

bool LoadFile(const char* path, std::vector<uint8_t>* out) {
  FILE* f = fopen(path, "rb");
  if (!f) {
    fprintf(stderr, "error: cannot open %s\n", path);
    return false;
  }
  fseek(f, 0, SEEK_END);
  long size = ftell(f);
  fseek(f, 0, SEEK_SET);
  if (size <= 0) {
    fprintf(stderr, "error: empty file %s\n", path);
    fclose(f);
    return false;
  }
  out->resize(static_cast<size_t>(size));
  size_t got = fread(out->data(), 1, out->size(), f);
  fclose(f);
  if (got != out->size()) {
    fprintf(stderr, "error: short read on %s (%zu/%zu)\n", path, got, out->size());
    return false;
  }
  return true;
}

// Registers every op the 6 zoo models can contain. The set is a documented
// superset of the op lists in models/zoo/DEFERRED_MODELS.md §5/§6 (conv,
// depthwise, avgpool, reshape, fc, softmax, add, mul, mean, pad, transpose,
// plus a few safety entries). If a model ever needs an op not listed here,
// tflite-micro reports "Op not found" and this list must grow.
tflite::MicroMutableOpResolver<24> BuildResolver() {
  tflite::MicroMutableOpResolver<24> resolver;
  resolver.AddConv2D();
  resolver.AddDepthwiseConv2D();
  resolver.AddAveragePool2D();
  resolver.AddMaxPool2D();
  resolver.AddReshape();
  resolver.AddFullyConnected();
  resolver.AddSoftmax();
  resolver.AddAdd();
  resolver.AddMul();
  resolver.AddSub();
  resolver.AddMean();
  resolver.AddPad();
  resolver.AddTranspose();
  resolver.AddQuantize();
  resolver.AddDequantize();
  resolver.AddConcatenation();
  resolver.AddRelu();
  resolver.AddRelu6();
  resolver.AddLogistic();
  resolver.AddLeakyRelu();
  resolver.AddPrelu();
  resolver.AddSplit();
  resolver.AddSlice();
  resolver.AddStridedSlice();
  return resolver;
}

bool RunCase(const ModelCase& c) {
  const std::string model_path = ResolvePath(c.tflite_path);
  const std::string input_path = ResolvePath(c.input_bin_path);
  std::vector<uint8_t> model_data;
  if (!LoadFile(model_path.c_str(), &model_data)) return false;

  const tflite::Model* model = tflite::GetModel(model_data.data());
  if (model == nullptr || model->subgraphs() == nullptr ||
      model->subgraphs()->size() == 0) {
    fprintf(stderr, "error: %s: not a valid tflite flatbuffer\n", c.name);
    return false;
  }
  if (model->version() != TFLITE_SCHEMA_VERSION) {
    // Older schema versions still run (flatbuffers are forward-compatible);
    // log but do not bail, mirroring tflite-micro's own tolerance in tests.
    printf("note: %s: model schema version %d != TFLM %d\n", c.name,
           static_cast<int>(model->version()), TFLITE_SCHEMA_VERSION);
  }

  std::vector<uint8_t> input_bytes;
  if (!LoadFile(input_path.c_str(), &input_bytes)) return false;
  if (input_bytes.size() != c.input_bytes) {
    fprintf(stderr,
            "error: %s: input .bin has %zu bytes but golden INPUT_DATA has "
            "%zu elements — input extraction is not byte-identical\n",
            c.name, input_bytes.size(), c.input_bytes);
    return false;
  }

  // Host-only harness: arena is heap-allocated (16-byte aligned by malloc).
  uint8_t* arena = static_cast<uint8_t*>(malloc(c.arena_bytes));
  if (arena == nullptr) {
    fprintf(stderr, "error: %s: cannot allocate %zu-byte arena\n", c.name,
            c.arena_bytes);
    return false;
  }

  tflite::MicroMutableOpResolver<24> resolver = BuildResolver();
  tflite::MicroInterpreter interpreter(model, resolver, arena, c.arena_bytes);
  if (interpreter.AllocateTensors() != kTfLiteOk) {
    fprintf(stderr,
            "error: %s: AllocateTensors failed (arena %zu bytes too small?)\n",
            c.name, c.arena_bytes);
    free(arena);
    return false;
  }

  if (interpreter.inputs_size() != 1) {
    fprintf(stderr, "error: %s: expected exactly 1 input tensor, got %zu\n",
            c.name, interpreter.inputs_size());
    free(arena);
    return false;
  }
  TfLiteTensor* input = interpreter.input(0);
  if (input->bytes != c.input_bytes) {
    fprintf(stderr,
            "error: %s: model input tensor is %zu bytes but golden INPUT_DATA "
            "is %zu elements\n",
            c.name, input->bytes, c.input_bytes);
    free(arena);
    return false;
  }
  memcpy(input->data.data, input_bytes.data(), input_bytes.size());

  if (interpreter.Invoke() != kTfLiteOk) {
    fprintf(stderr, "error: %s: Invoke failed\n", c.name);
    free(arena);
    return false;
  }

  TfLiteTensor* out = interpreter.output(0);
  size_t n = out->bytes;
  const int8_t* data = out->data.int8;

  // Canonical, parseable output format (consumed by the golden generator):
  //   == MODEL <name> ==
  //   input_shape: 1 1960
  //   output_shape: 1 4
  //   output: -64,-64,-64,-64
  //   fnv1a: 0x3a24ca75 (975504501)
  printf("== MODEL %s ==\n", c.name);
  printf("input_shape:");
  for (int d = 0; d < input->dims->size; ++d) {
    printf(" %d", input->dims->data[d]);
  }
  printf("\noutput_shape:");
  for (int d = 0; d < out->dims->size; ++d) {
    printf(" %d", out->dims->data[d]);
  }
  printf("\noutput:");
  for (size_t i = 0; i < n; ++i) {
    printf("%s%d", i == 0 ? "" : ",", static_cast<int>(data[i]));
  }
  printf("\nfnv1a: 0x%08x (%u)\n", Fnv1a(data, n), Fnv1a(data, n));

  free(arena);
  return true;
}

}  // namespace

int main(int argc, char** argv) {
  g_base_dir = DirNameOf(argc > 0 ? argv[0] : "");
  const size_t kNumCases = sizeof(kCases) / sizeof(kCases[0]);
  printf("tflm-goldens harness: %zu model case(s)\n", kNumCases);
  bool ok = true;
  for (size_t i = 0; i < kNumCases; ++i) {
    if (!RunCase(kCases[i])) ok = false;
  }
  printf(ok ? "HARNESS: ALL MODELS RAN\n" : "HARNESS: FAILURES ABOVE\n");
  return ok ? 0 : 1;
}
