#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Hematite Contributors.
"""Generate a minimal int8 TFLite model for testing hematite-codegen.

This is a DEV-time script — the output model is committed, never fetched at build time.

Model: 1-element INT8 input → FullyConnected (1×1 weight, 1 bias) → 1-element INT8 output.
Weights=51 (~0.4 × 128, Q7), bias=-3, scale=0.1 both sides.

Provenance: Generated by tools/generate_sine_model.py.
"""

from flatbuffers import Builder

INT8 = 9
INT32 = 2
FULLY_CONNECTED = 9  # BuiltinOperator
# Union BuiltinOptions member numbers (schema.fbs, v2.14.1-era): the union
# discriminator is written into vtable slot 3 (builtin_options_type), the
# union value (a table uoffset) into slot 4 (builtin_options).
FULLYCONNECTEDOPTIONS = 8
ACT_NONE = 0
FC_DEFAULT = 0


def generate():
    """Build the model with flatbuffers.Builder."""
    b = Builder(2048)
    
    # === Helper to avoid the ugly `or 0` pattern ===
    def make_int32_vector(values):
        n = len(values)
        b.StartVector(4, n, 4)
        for v in reversed(values):
            b.PrependInt32(v)
        return b.EndVector(n)

    def make_int64_vector(values):
        n = len(values)
        b.StartVector(8, n, 8)
        for v in reversed(values):
            b.PrependInt64(v)
        return b.EndVector(n)

    def make_float_vector(values):
        n = len(values)
        b.StartVector(4, n, 4)
        for v in reversed(values):
            b.PrependFloat32(v)
        return b.EndVector(n)

    def make_table_vector(tables):
        n = len(tables)
        b.StartVector(4, n, 4)
        for t in reversed(tables):
            b.PrependUOffsetTRelative(t)
        return b.EndVector(n)

    # === BUFFER DATA ===
    # Buffer 2: weights [51] (int8 / ubyte vector)
    # Buffer 3: bias [-3] (int32 LE — passed as raw bytes since flatbuffers stores ubyte)
    buf2_data = b.CreateByteVector(bytes([51]))
    buf3_data = b.CreateByteVector((-3).to_bytes(4, 'little', signed=True))

    # === QUANTIZATION for input tensor ===
    zp_vec = make_int64_vector([0])
    scale_vec = make_float_vector([0.1])
    b.StartObject(6)
    b.PrependUOffsetTRelativeSlot(5, 0, 0)  # quantized_dimension
    b.PrependUOffsetTRelativeSlot(4, 0, 0)  # details
    b.PrependUOffsetTRelativeSlot(3, zp_vec, 0)
    b.PrependUOffsetTRelativeSlot(2, scale_vec, 0)
    input_quant = b.EndObject()

    # === QUANTIZATION for weights tensor ===
    w_zp_vec = make_int64_vector([0])
    w_scale_vec = make_float_vector([0.0078125])  # 1/128
    b.StartObject(6)
    b.PrependUOffsetTRelativeSlot(5, 0, 0)
    b.PrependUOffsetTRelativeSlot(4, 0, 0)
    b.PrependUOffsetTRelativeSlot(3, w_zp_vec, 0)
    b.PrependUOffsetTRelativeSlot(2, w_scale_vec, 0)
    weight_quant = b.EndObject()

    # === QUANTIZATION for output tensor ===
    o_zp_vec = make_int64_vector([0])
    o_scale_vec = make_float_vector([0.1])
    b.StartObject(6)
    b.PrependUOffsetTRelativeSlot(5, 0, 0)
    b.PrependUOffsetTRelativeSlot(4, 0, 0)
    b.PrependUOffsetTRelativeSlot(3, o_zp_vec, 0)
    b.PrependUOffsetTRelativeSlot(2, o_scale_vec, 0)
    output_quant = b.EndObject()

    # === TENSORS ===
    # Tensor 0: input
    t0_shape = make_int32_vector([1])
    t0_name = b.CreateString("input")
    b.StartObject(7)
    b.PrependBoolSlot(5, False, False)  # is_variable
    b.PrependUOffsetTRelativeSlot(4, input_quant, 0)
    b.PrependUOffsetTRelativeSlot(3, t0_name, 0)
    b.PrependUint32Slot(2, 1, 0)  # buffer=1
    b.PrependInt8Slot(1, INT8, 0)
    b.PrependUOffsetTRelativeSlot(0, t0_shape, 0)
    tensor0 = b.EndObject()

    # Tensor 1: weights
    t1_shape = make_int32_vector([1, 1])
    t1_name = b.CreateString("fc/weights")
    b.StartObject(7)
    b.PrependBoolSlot(5, False, False)
    b.PrependUOffsetTRelativeSlot(4, weight_quant, 0)
    b.PrependUOffsetTRelativeSlot(3, t1_name, 0)
    b.PrependUint32Slot(2, 2, 0)  # buffer=2
    b.PrependInt8Slot(1, INT8, 0)
    b.PrependUOffsetTRelativeSlot(0, t1_shape, 0)
    tensor1 = b.EndObject()

    # Tensor 2: bias
    t2_shape = make_int32_vector([1])
    t2_name = b.CreateString("fc/bias")
    b.StartObject(7)
    b.PrependBoolSlot(5, False, False)
    b.PrependUOffsetTRelativeSlot(4, 0, 0)  # no quantization for bias
    b.PrependUOffsetTRelativeSlot(3, t2_name, 0)
    b.PrependUint32Slot(2, 3, 0)  # buffer=3
    b.PrependInt8Slot(1, INT32, 0)
    b.PrependUOffsetTRelativeSlot(0, t2_shape, 0)
    tensor2 = b.EndObject()

    # Tensor 3: output
    t3_shape = make_int32_vector([1])
    t3_name = b.CreateString("output")
    b.StartObject(7)
    b.PrependBoolSlot(5, False, False)
    b.PrependUOffsetTRelativeSlot(4, output_quant, 0)
    b.PrependUOffsetTRelativeSlot(3, t3_name, 0)
    b.PrependUint32Slot(2, 0, 0)  # buffer=0 (empty, output)
    b.PrependInt8Slot(1, INT8, 0)
    b.PrependUOffsetTRelativeSlot(0, t3_shape, 0)
    tensor3 = b.EndObject()

    sg_tensors_vec = make_table_vector([tensor0, tensor1, tensor2, tensor3])

    # === FULLY CONNECTED OPTIONS ===
    b.StartObject(3)
    b.PrependBoolSlot(2, False, False)  # keep_num_dims
    b.PrependInt8Slot(1, FC_DEFAULT, FC_DEFAULT)  # weights_format
    b.PrependInt8Slot(0, ACT_NONE, ACT_NONE)  # fused_activation_function
    fc_opts = b.EndObject()

    # === OPERATOR ===
    # Operator table (schema.fbs): slot 0 opcode_index, 1 inputs, 2 outputs,
    # 3 builtin_options_type (union discriminator), 4 builtin_options (uoffset).
    op_inputs_vec = make_int32_vector([0, 1, 2])
    op_outputs_vec = make_int32_vector([3])
    b.StartObject(6)
    b.PrependUOffsetTRelativeSlot(4, fc_opts, 0)  # builtin_options
    b.PrependUint8Slot(3, FULLYCONNECTEDOPTIONS, 0)  # builtin_options_type
    b.PrependUOffsetTRelativeSlot(2, op_outputs_vec, 0)
    b.PrependUOffsetTRelativeSlot(1, op_inputs_vec, 0)
    b.PrependUint32Slot(0, 0, 0)  # opcode_index
    op0 = b.EndObject()
    sg_ops_vec = make_table_vector([op0])

    # === SUBGRAPH ===
    sg_inputs_vec = make_int32_vector([0])
    sg_outputs_vec = make_int32_vector([3])
    sg_name = b.CreateString("main")
    b.StartObject(5)
    b.PrependUOffsetTRelativeSlot(4, sg_name, 0)
    b.PrependUOffsetTRelativeSlot(3, sg_ops_vec, 0)
    b.PrependUOffsetTRelativeSlot(2, sg_outputs_vec, 0)
    b.PrependUOffsetTRelativeSlot(1, sg_inputs_vec, 0)
    b.PrependUOffsetTRelativeSlot(0, sg_tensors_vec, 0)
    subgraph0 = b.EndObject()
    sg_vec = make_table_vector([subgraph0])

    # === OPERATOR CODE ===
    # OperatorCode: deprecated_builtin_code(0), custom_code(1), version(2), builtin_code(3)
    b.StartObject(4)
    b.PrependInt32Slot(3, FULLY_CONNECTED, 0)  # builtin_code
    b.PrependInt32Slot(2, 1, 1)  # version = 1
    # skip custom_code(1)
    # skip deprecated_builtin_code(0)
    opcode0 = b.EndObject()
    opcodes_vec = make_table_vector([opcode0])

    # === BUFFERS ===
    b.StartObject(3)
    buf0 = b.EndObject()  # Buffer 0: empty sentinel

    b.StartObject(3)
    buf1 = b.EndObject()  # Buffer 1: empty (input placeholder)

    b.StartObject(3)
    b.PrependUOffsetTRelativeSlot(0, buf2_data, 0)
    buf2 = b.EndObject()  # Buffer 2: contains weight data

    b.StartObject(3)
    b.PrependUOffsetTRelativeSlot(0, buf3_data, 0)
    buf3 = b.EndObject()  # Buffer 3: contains bias data

    bufs_vec = make_table_vector([buf0, buf1, buf2, buf3])

    # === MODEL ===
    # Model: version(0), operator_codes(1), subgraphs(2), description(3), buffers(4),
    #        metadata_buffer(5), metadata(6), signature_defs(7)
    b.StartObject(8)
    b.PrependUOffsetTRelativeSlot(4, bufs_vec, 0)
    b.PrependUOffsetTRelativeSlot(2, sg_vec, 0)
    b.PrependUOffsetTRelativeSlot(1, opcodes_vec, 0)
    b.PrependUint32Slot(0, 3, 0)  # version = 3
    model = b.EndObject()

    # === FINISH ===
    b.Finish(model, file_identifier=b'TFL3')
    return b.Output()


if __name__ == "__main__":
    buf = generate()
    import sys
    out_path = sys.argv[1] if len(sys.argv) > 1 else "models/sine.tflite"
    with open(out_path, "wb") as f:
        f.write(buf)
    print(f"Written {len(buf)} bytes to {out_path}")
    print(f"First 8 bytes: {buf[:8].hex()}")
