#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Hematite Contributors.
"""Generate the T5.1 T2-divergence fixture model for the fused==unfused harness.

This is a DEV-time script — the output model is committed, never fetched at
build time (the generate_sine_model.py precedent).

Model: TWO int8 graph inputs [1,4,4,16] -> MUL(input0, input1, fused RELU) ->
MAX_POOL_2D(2x2/stride-2/SAME) -> INT8 output [1,2,2,16].

Why this shape (T5.1 auto-unfuse proof):

* The MUL's fused RELU is the GENUINE divergence source.  The per-op
  sequence clamps the MUL output to the RELU range [0,127]; the composed
  `fused_pool_with_fold` fold materialization (and the T2.4 golden-matrix
  decomposition) clamps full-range [-128,127] — the fold params carry no
  activation fields.  A window whose elements are all negative max-pools to
  0 per-op vs a negative value composed: the composed emission diverges.
* Quant: input0 scale 1.0, input1 (operand) scale 0.5, MUL output scale 0.5
  (=> folded_scale = s_out/s_in = 0.5, non-identity), zero points all 0.
  The MUL's output ratio is qm(1.0*0.5/0.5) = (1<<30, 0) — the T2.4
  provably-exact subset, so the T4.1 mirror gate (pool 2x2/stride-2/SAME,
  channels % 16, identity fold) says SIMD-eligible: the ONLY thing standing
  between this group and a composed emission is the T2
  `requires_verification` flag (fusion.rs) — exactly the W5 flip surface
  the harness proves.
* The operand is a SECOND GRAPH INPUT, not a constant: the T4.1 per-op
  emitter rejects constant data as elementwise op inputs (generate.rs
  src_expr "constant data inputs are not supported in T4.1 (deferred to
  T4.2a fusion)"), and the auto-unfused re-emission IS the per-op path.
  MUL input folds do not require a constant operand (try_input_fold only
  reads the constant buffer for SUB folds).
* The 2x2/stride-2/SAME pool over 4x4 has pad_total 0 and area 4
  (`pool_area_inv(4)` present) -> `simd_eligible_pool` passes.

Provenance: Generated by tools/generate_t2_fold_fixture.py.
"""

from flatbuffers import Builder

INT8 = 9
MUL = 18        # BuiltinOperator
MAX_POOL_2D = 17
# Union BuiltinOptions member numbers (schema.fbs): Pool2DOptions = 4,
# MulOptions = 20 (0 Conv2D, 1 Depthwise, 2 ConcatEmbed, 3 LSH, 4 Pool2D,
# 5 SVDF, 6 RNN, 7 FC, 8 Softmax, 9 Concat, 10 Add, 11 L2Norm, 12 LRN,
# 13 LSTM, 14 ResizeBilinear, 15 Call, 16 Reshape, 17 SkipGram,
# 18 SpaceToDepth, 19 EmbeddingLookupSparse, 20 MulOptions, 21 Pad, ...).
# The hematite flatbuffer parser dispatches on builtin_code, so the
# discriminator only needs to be non-zero — but stay faithful to the schema.
POOL2D_OPTIONS = 4
MUL_OPTIONS = 20
ACT_NONE = 0
ACT_RELU = 1
PAD_SAME = 0

def generate():
    """Build the model with flatbuffers.Builder."""
    b = Builder(4096)

    def make_int32_vector(values):
        n = len(values)
        b.StartVector(4, n, 4)
        for v in reversed(values):
            b.PrependInt32(v)
        return b.EndVector(n)

    def make_int64_vector(values):
        n = len(values)
        b.StartVector(8, n, 8)
        for v in reversed(values):
            b.PrependInt64(v)
        return b.EndVector(n)

    def make_float_vector(values):
        n = len(values)
        b.StartVector(4, n, 4)
        for v in reversed(values):
            b.PrependFloat32(v)
        return b.EndVector(n)

    def make_table_vector(tables):
        n = len(tables)
        b.StartVector(4, n, 4)
        for t in reversed(tables):
            b.PrependUOffsetTRelative(t)
        return b.EndVector(n)

    def quant(scale, zp):
        zp_vec = make_int64_vector([zp])
        scale_vec = make_float_vector([scale])
        b.StartObject(6)
        b.PrependUOffsetTRelativeSlot(5, 0, 0)  # quantized_dimension
        b.PrependUOffsetTRelativeSlot(4, 0, 0)  # details
        b.PrependUOffsetTRelativeSlot(3, zp_vec, 0)
        b.PrependUOffsetTRelativeSlot(2, scale_vec, 0)
        return b.EndObject()

    # === TENSORS ===
    shape_4x4x16 = make_int32_vector([1, 4, 4, 16])
    shape_2x2x16 = make_int32_vector([1, 2, 2, 16])

    def tensor(name, shape, buffer_idx, tensor_quant, type_code):
        name_off = b.CreateString(name)
        b.StartObject(7)
        b.PrependBoolSlot(5, False, False)  # is_variable
        b.PrependUOffsetTRelativeSlot(4, tensor_quant, 0)
        b.PrependUOffsetTRelativeSlot(3, name_off, 0)
        b.PrependUint32Slot(2, buffer_idx, 0)
        b.PrependInt8Slot(1, type_code, 0)
        b.PrependUOffsetTRelativeSlot(0, shape, 0)
        return b.EndObject()

    # T0: input0 [1,4,4,16] int8 scale 1.0 zp 0 (buffer 0 empty).
    t0 = tensor("input", shape_4x4x16, 0, quant(1.0, 0), INT8)
    # T1: input1 = MUL operand [1,4,4,16] int8 scale 0.5 zp 0 (graph input).
    t1 = tensor("mul/operand", shape_4x4x16, 0, quant(0.5, 0), INT8)
    # T2: MUL output [1,4,4,16] int8 scale 0.5 zp 0 (intermediate).
    t2 = tensor("mul/out", shape_4x4x16, 0, quant(0.5, 0), INT8)
    # T3: pool output [1,2,2,16] int8 scale 0.5 zp 0 (output).
    t3 = tensor("pool/max", shape_2x2x16, 0, quant(0.5, 0), INT8)

    sg_tensors_vec = make_table_vector([t0, t1, t2, t3])

    # === MUL OPTIONS (fused_activation_function = RELU) ===
    b.StartObject(1)
    b.PrependInt8Slot(0, ACT_RELU, ACT_NONE)
    mul_opts = b.EndObject()

    # === POOL2D OPTIONS (2x2 / stride 2 / SAME / no activation) ===
    b.StartObject(8)
    b.PrependInt8Slot(0, PAD_SAME, PAD_SAME)   # padding
    b.PrependInt32Slot(1, 2, 1)                # stride_w
    b.PrependInt32Slot(2, 2, 1)                # stride_h
    b.PrependInt32Slot(3, 2, 1)                # filter_width
    b.PrependInt32Slot(4, 2, 1)                # filter_height
    b.PrependInt8Slot(5, ACT_NONE, ACT_NONE)   # fused_activation_function
    pool_opts = b.EndObject()

    # === OPERATORS ===
    op0_inputs = make_int32_vector([0, 1])
    op0_outputs = make_int32_vector([2])
    b.StartObject(6)
    b.PrependUOffsetTRelativeSlot(4, mul_opts, 0)   # builtin_options
    b.PrependUint8Slot(3, MUL_OPTIONS, 0)           # builtin_options_type
    b.PrependUOffsetTRelativeSlot(2, op0_outputs, 0)
    b.PrependUOffsetTRelativeSlot(1, op0_inputs, 0)
    b.PrependUint32Slot(0, 0, 0)                    # opcode_index
    op0 = b.EndObject()

    op1_inputs = make_int32_vector([2])
    op1_outputs = make_int32_vector([3])
    b.StartObject(6)
    b.PrependUOffsetTRelativeSlot(4, pool_opts, 0)  # builtin_options
    b.PrependUint8Slot(3, POOL2D_OPTIONS, 0)        # builtin_options_type
    b.PrependUOffsetTRelativeSlot(2, op1_outputs, 0)
    b.PrependUOffsetTRelativeSlot(1, op1_inputs, 0)
    b.PrependUint32Slot(0, 1, 0)                    # opcode_index
    op1 = b.EndObject()

    sg_ops_vec = make_table_vector([op0, op1])

    # === SUBGRAPH ===
    sg_inputs_vec = make_int32_vector([0, 1])
    sg_outputs_vec = make_int32_vector([3])
    sg_name = b.CreateString("main")
    b.StartObject(5)
    b.PrependUOffsetTRelativeSlot(4, sg_name, 0)
    b.PrependUOffsetTRelativeSlot(3, sg_ops_vec, 0)
    b.PrependUOffsetTRelativeSlot(2, sg_outputs_vec, 0)
    b.PrependUOffsetTRelativeSlot(1, sg_inputs_vec, 0)
    b.PrependUOffsetTRelativeSlot(0, sg_tensors_vec, 0)
    subgraph0 = b.EndObject()
    sg_vec = make_table_vector([subgraph0])

    # === OPERATOR CODES ===
    b.StartObject(4)
    b.PrependInt32Slot(3, MUL, 0)        # builtin_code
    b.PrependInt32Slot(2, 1, 1)          # version = 1
    opcode0 = b.EndObject()
    b.StartObject(4)
    b.PrependInt32Slot(3, MAX_POOL_2D, 0)
    b.PrependInt32Slot(2, 1, 1)
    opcode1 = b.EndObject()
    opcodes_vec = make_table_vector([opcode0, opcode1])

    # === BUFFERS (all empty — both inputs are graph inputs) ===
    b.StartObject(3)
    buf0 = b.EndObject()
    bufs_vec = make_table_vector([buf0])

    # === MODEL ===
    b.StartObject(8)
    b.PrependUOffsetTRelativeSlot(4, bufs_vec, 0)
    b.PrependUOffsetTRelativeSlot(2, sg_vec, 0)
    b.PrependUOffsetTRelativeSlot(1, opcodes_vec, 0)
    b.PrependUint32Slot(0, 3, 0)  # version = 3
    model = b.EndObject()

    # === FINISH ===
    b.Finish(model, file_identifier=b"TFL3")
    return b.Output()


if __name__ == "__main__":
    buf = generate()
    import sys
    out_path = sys.argv[1] if len(sys.argv) > 1 else "hematite-codegen/tests/fixtures/t2_fold_divergence_int8.tflite"
    with open(out_path, "wb") as f:
        f.write(buf)
    print(f"Written {len(buf)} bytes to {out_path}")
    print(f"First 8 bytes: {buf[:8].hex()}")
