//! Fixture file writer — emits Rust const-array source files.

use std::fmt::Write as FmtWrite;

pub const SPDX_HEADER: &str = r#"// SPDX-License-Identifier: Apache-2.0
// Copyright 2024 The TensorFlow Authors. All Rights Reserved.
// Copyright 2026 Hematite Contributors.
//
// This file contains golden reference output values for TFLite Micro operator
// verification. Generated by tools/generate_goldens.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
"#;

pub const TFLM_VERSION: &str = "18b9e6f2a8c5a9518e588f59c2ba16ef7ef9d551";

pub const PROVENANCE_NOTE: &str = "\
// ═══════════════════════════════════════════════════════════════════════════════
// WARNING: TOOL-INTERNAL REFERENCE VALUES — NOT CAPTURED FROM EXECUTED TFLM
//
// The values in this file were generated by a scalar reimplementation of the
// TFLite Micro int8 reference kernels, NOT by capturing output from an
// executed TFLM binary. They are faithful to the TFLM arithmetic specification
// (i32 accumulate, MultiplyByQuantizedMultiplier with saturating rounding
// doubling high-mul, per-channel requantize, saturating cast, zero-point
// offset handling, fused-activation clamping) but have NOT been cross-validated
// against a running TFLM interpreter.
//
// T5.0 MUST re-generate the golden corpus against a real executed TFLM build
// at the pinned SHA before any public bit-exactness claim is made, or before
// any Phase 5 benchmarking conclusions are drawn.
//
// This provenance note is non-negotiable and must be removed ONLY by T5.0
// after real-TFLM regeneration.
// ═══════════════════════════════════════════════════════════════════════════════
";

/// Write a Rust const-array fixture file for one op.
pub struct FixtureWriter {
    output_dir: std::path::PathBuf,
}

impl FixtureWriter {
    /// Return the output directory path (for ops that need custom provenance).
    pub fn output_dir(&self) -> &std::path::PathBuf {
        &self.output_dir
    }
}

impl FixtureWriter {
    pub fn new(output_dir: std::path::PathBuf) -> Self {
        std::fs::create_dir_all(&output_dir).expect("create goldens dir");
        Self { output_dir }
    }

    #[allow(clippy::too_many_arguments)]
    pub fn write(
        &mut self,
        name: &str,
        input_shape: &[i32; 4],
        filter_shape: &[i32; 4],
        output_shape: &[i32; 4],
        input_data: &[i8],
        weights_data: &[i8],
        bias_data: &[i32],
        input_offset: i32,
        output_offset: i32,
        output_activation_min: i32,
        output_activation_max: i32,
        output_multiplier: &[i32],
        output_shift: &[i32],
        expected_output: &[i8],
        extra_params: &[(&str, i32)],
    ) {
        let mut buf = String::with_capacity(16384);
        buf.push_str(SPDX_HEADER);
        buf.push('\n');
        buf.push_str(PROVENANCE_NOTE);
        buf.push('\n');

        buf.push_str(&format!(
            "/// TFLite Micro pin that defines this golden corpus.\n\
             pub const GOLDEN_TFLM_VERSION: &str = \"{TFLM_VERSION}\";\n\n"
        ));

        buf.push_str(
            "/// Provenance of these golden values.\n\
             pub const GOLDEN_PROVENANCE: &str = \"tool-internal-reference-reimplementation; NOT captured from executed TFLM; see tools/generate_goldens/README.md\";\n\n"
        );

        // Shapes
        buf.push_str(&format!(
            "pub const INPUT_SHAPE: [i32; 4] = {input_shape:?};\n"
        ));
        buf.push_str(&format!(
            "pub const FILTER_SHAPE: [i32; 4] = {filter_shape:?};\n"
        ));
        buf.push_str(&format!(
            "pub const OUTPUT_SHAPE: [i32; 4] = {output_shape:?};\n\n"
        ));

        // Extra params (stride, padding, dilation)
        for (key, val) in extra_params {
            buf.push_str(&format!(
                "pub const {}: i32 = {};\n",
                key.to_uppercase(), val
            ));
        }
        buf.push('\n');

        // Quantization parameters
        buf.push_str(&format!(
            "pub const INPUT_OFFSET: i32 = {input_offset};\n"
        ));
        buf.push_str(&format!(
            "pub const OUTPUT_OFFSET: i32 = {output_offset};\n"
        ));
        buf.push_str(&format!(
            "pub const OUTPUT_ACTIVATION_MIN: i32 = {output_activation_min};\n"
        ));
        buf.push_str(&format!(
            "pub const OUTPUT_ACTIVATION_MAX: i32 = {output_activation_max};\n\n"
        ));

        // Data arrays
        emit_const_array(&mut buf, "INPUT_DATA", "i8", input_data);
        emit_const_array(&mut buf, "WEIGHTS_DATA", "i8", weights_data);
        emit_const_array(&mut buf, "BIAS_DATA", "i32", bias_data);
        emit_const_array(&mut buf, "OUTPUT_MULTIPLIER", "i32", output_multiplier);
        emit_const_array(&mut buf, "OUTPUT_SHIFT", "i32", output_shift);
        emit_const_array(&mut buf, "EXPECTED_OUTPUT", "i8", expected_output);

        let path = self.output_dir.join(format!("{name}.rs"));
        std::fs::write(&path, buf).expect("write fixture");
        println!("  Wrote {}", path.display());
    }

    /// Write a simple fixture with no weights/bias (activations, data movement, quant).
    #[allow(clippy::too_many_arguments)]
    pub fn write_simple(
        &mut self,
        name: &str,
        input_shape: &[i32; 4],
        output_shape: &[i32; 4],
        input_data: &[i8],
        expected_output: &[i8],
        extra_params: &[(&str, i32)],
        description: &str,
    ) {
        let mut buf = String::with_capacity(8192);
        buf.push_str(SPDX_HEADER);
        buf.push('\n');
        buf.push_str(PROVENANCE_NOTE);
        buf.push('\n');

        buf.push_str(&format!(
            "/// TFLite Micro pin that defines this golden corpus.\n\
             pub const GOLDEN_TFLM_VERSION: &str = \"{TFLM_VERSION}\";\n\n"
        ));

        buf.push_str(
            "/// Provenance of these golden values.\n\
             pub const GOLDEN_PROVENANCE: &str = \"tool-internal-reference-reimplementation; NOT captured from executed TFLM; see tools/generate_goldens/README.md\";\n\n"
        );

        buf.push_str(&format!(
            "pub const INPUT_SHAPE: [i32; 4] = {input_shape:?};\n"
        ));
        buf.push_str(&format!(
            "pub const OUTPUT_SHAPE: [i32; 4] = {output_shape:?};\n\n"
        ));

        for (key, val) in extra_params {
            buf.push_str(&format!(
                "pub const {}: i32 = {};\n",
                key.to_uppercase(), val
            ));
        }
        buf.push('\n');

        buf.push_str(description);
        buf.push('\n');

        emit_const_array(&mut buf, "INPUT_DATA", "i8", input_data);
        emit_const_array(&mut buf, "EXPECTED_OUTPUT", "i8", expected_output);

        let path = self.output_dir.join(format!("{name}.rs"));
        std::fs::write(&path, buf).expect("write fixture");
        println!("  Wrote {}", path.display());
    }

    /// Write a per-model golden fixture captured from an executed TFLite
    /// interpreter (ai-edge-litert) via `zoo/run_model.py`.
    ///
    /// Unlike op fixtures, model fixtures carry REAL executed-TFLite
    /// provenance: the output was captured by running the model, not by
    /// tool-internal reimplementation. Emitted under `goldens/models/`.
    #[allow(clippy::too_many_arguments)]
    pub fn write_model(
        &mut self,
        name: &str,
        input_shape: &[i32],
        output_shape: &[i32],
        input_data: &[i8],
        expected_output: &[i8],
        runtime_version: &str,
        model_rel_path: &str,
    ) {        let mut buf = String::with_capacity(16384);
        buf.push_str(SPDX_HEADER);
        buf.push('\n');
        buf.push_str(&format!(
            "// ═══════════════════════════════════════════════════════════════\n\
             // CAPTURED FROM EXECUTED TFLITE — REAL MODEL OUTPUT\n\
             //\n\
             // This fixture is a per-model golden: INPUT_DATA was run through\n\
             // the model {model_rel_path} via the TFLite interpreter\n\
             // (ai-edge-litert {runtime_version}), and EXPECTED_OUTPUT is the\n\
             // exact int8 output captured from that execution. This is NOT the\n\
             // tool-internal reimplementation path used by per-op fixtures.\n\
             // ═══════════════════════════════════════════════════════════════\n\n"
        ));

        buf.push_str(&format!(
            "/// TFLite Micro pin that defines this golden corpus.\n\
             pub const GOLDEN_TFLM_VERSION: &str = \"{TFLM_VERSION}\";\n\n"
        ));
        buf.push_str(&format!(
            "/// Interpreter that produced these values.\n\
             pub const GOLDEN_RUNTIME_VERSION: &str = \"{runtime_version}\";\n\n"
        ));
        buf.push_str(
            "/// Provenance: captured from an executed TFLite interpreter.\n\
             pub const GOLDEN_PROVENANCE: &str = \"captured-from-executed-TFLite-interpreter; see tools/generate_goldens/zoo/run_model.py\";\n\n"
        );

        buf.push_str(&format!(
            "/// Path to the model relative to the workspace root.\n\
             pub const MODEL_PATH: &str = \"{model_rel_path}\";\n\n"
        ));
        buf.push_str(&format!(
            "pub const INPUT_SHAPE: [i32; {}] = {:?};\n",
            input_shape.len(), input_shape
        ));
        buf.push_str(&format!(
            "pub const OUTPUT_SHAPE: [i32; {}] = {:?};\n\n",
            output_shape.len(), output_shape
        ));

        emit_const_array(&mut buf, "INPUT_DATA", "i8", input_data);
        emit_const_array(&mut buf, "EXPECTED_OUTPUT", "i8", expected_output);

        let dir = self.output_dir.join("models");
        std::fs::create_dir_all(&dir).expect("create goldens/models dir");
        let path = dir.join(format!("{name}.rs"));
        std::fs::write(&path, buf).expect("write model fixture");
        println!("  Wrote {}", path.display());
    }

    /// Write a per-model golden fixture captured from EXECUTED tflite-micro
    /// at the pinned SHA via the `tools/tflm-goldens` host harness (todo T10
    /// regeneration; retires the ai-edge-litert provenance of `write_model`).
    /// The `model_rel_path`/`input_data` come from the PRE-EXISTING golden
    /// (inputs are unchanged); `expected_output` comes from the harness output
    /// VERBATIM. Emitted under `goldens/models/`.
    #[allow(clippy::too_many_arguments)]
    pub fn write_model_tflm(
        &mut self,
        name: &str,
        input_shape: &[i32],
        output_shape: &[i32],
        input_data: &[i8],
        expected_output: &[i8],
        model_rel_path: &str,
    ) {
        let mut buf = String::with_capacity(16384);
        buf.push_str(SPDX_HEADER);
        buf.push('\n');
        buf.push_str(&format!(
            "// ═══════════════════════════════════════════════════════════════\n\
             // CAPTURED FROM EXECUTED TFLITE-MICRO — REAL MODEL OUTPUT\n\
             //\n\
             // This fixture is a per-model golden: INPUT_DATA was run through\n\
             // the model {model_rel_path} via the EXECUTED tflite-micro\n\
             // interpreter (tools/tflm-goldens host harness, reference kernels,\n\
             // pinned SHA below), and EXPECTED_OUTPUT is the exact int8 output\n\
             // captured from that execution. This retires the previous\n\
             // ai-edge-litert (LiteRT) interpreter provenance.\n\
             // ═══════════════════════════════════════════════════════════════\n\n"
        ));

        buf.push_str(&format!(
            "/// TFLite Micro pin that defines this golden corpus.\n\
             pub const GOLDEN_TFLM_VERSION: &str = \"{TFLM_VERSION}\";\n\n"
        ));
        buf.push_str(&format!(
            "/// Executed interpreter that produced these values.\n\
             pub const GOLDEN_RUNTIME_VERSION: &str = \"tflite-micro @ {TFLM_VERSION} (executed, reference kernels)\";\n\n"
        ));
        buf.push_str(
            "/// Provenance: captured from executed tflite-micro at the pinned\n\
             /// SHA via the tools/tflm-goldens host harness.\n\
             pub const GOLDEN_PROVENANCE: &str = \"captured-from-executed-tflite-micro @ 18b9e6f2a8c5a9518e588f59c2ba16ef7ef9d551; date 2026-08-10; cmd: (cd tools/tflm-goldens && make TFLM_ROOT=/tmp/tflite-micro run > generated/harness_output.txt)\";\n\n"
        );

        buf.push_str(&format!(
            "/// Path to the model relative to the workspace root.\n\
             pub const MODEL_PATH: &str = \"{model_rel_path}\";\n\n"
        ));
        buf.push_str(&format!(
            "pub const INPUT_SHAPE: [i32; {}] = {:?};\n",
            input_shape.len(), input_shape
        ));
        buf.push_str(&format!(
            "pub const OUTPUT_SHAPE: [i32; {}] = {:?};\n\n",
            output_shape.len(), output_shape
        ));

        emit_const_array(&mut buf, "INPUT_DATA", "i8", input_data);
        emit_const_array(&mut buf, "EXPECTED_OUTPUT", "i8", expected_output);

        let dir = self.output_dir.join("models");
        std::fs::create_dir_all(&dir).expect("create goldens/models dir");
        let path = dir.join(format!("{name}.rs"));
        std::fs::write(&path, buf).expect("write model fixture");
        println!("  Wrote {}", path.display());
    }

    /// Re-tier the hard_swish op fixture: DOWNGRADED integer-rational
    /// approximation -> captured from EXECUTED tflite-micro HardSwish kernel
    /// (HardSwishParams chain) via the `tools/tflm-goldens` hard_swish
    /// micro-model (tools/tflm-goldens/models/hard_swish_int8.tflite; input
    /// scale 1.0/zp 0, output scale 1.0/zp 0). `expected_output` is the
    /// harness output VERBATIM. Emitted at `goldens/hard_swish.rs`.
    pub fn write_hard_swish_tflm(
        &mut self,
        input_data: &[i8],
        expected_output: &[i8],
    ) {
        let mut buf = String::with_capacity(8192);
        buf.push_str(SPDX_HEADER);
        buf.push('\n');
        buf.push_str(
            "// ═══════════════════════════════════════════════════════════════\n\
             // CAPTURED FROM EXECUTED TFLITE-MICRO — HARD_SWISH OP (RE-TIERED T10)\n\
             //\n\
             // Previously DOWNGRADED (integer-div-rational-approx, NOT\n\
             // TFLM-faithful). Now re-tiered: INPUT_DATA was run through the\n\
             // HardSwish micro-model tools/tflm-goldens/models/hard_swish_int8.tflite\n\
             // (int8, input scale 1.0 / zero-point 0, output scale 1.0 /\n\
             // zero-point 0) via the EXECUTED tflite-micro reference HardSwish\n\
             // kernel (HardSwishParams chain: SaturatingDoublingHighMul /\n\
             // SaturatingRoundingDoublingHighMul / RoundingDivideByPOT, see\n\
             // tensorflow/lite/kernels/internal/reference/hard_swish.h at the\n\
             // pinned SHA). EXPECTED_OUTPUT is the exact int8 output captured\n\
             // from that execution (VERBATIM).\n\
             // ═══════════════════════════════════════════════════════════════\n\n"
        );

        buf.push_str(&format!(
            "/// TFLite Micro pin that defines this golden corpus.\n\
             pub const GOLDEN_TFLM_VERSION: &str = \"{TFLM_VERSION}\";\n\n"
        ));
        buf.push_str(&format!(
            "/// Executed interpreter that produced these values.\n\
             pub const GOLDEN_RUNTIME_VERSION: &str = \"tflite-micro @ {TFLM_VERSION} (executed, reference kernels)\";\n\n"
        ));
        buf.push_str(
            "/// Provenance: captured from executed tflite-micro at the pinned\n\
             /// SHA via the tools/tflm-goldens host harness (hard_swish\n\
             /// micro-model case).\n\
             pub const GOLDEN_PROVENANCE: &str = \"captured-from-executed-tflite-micro @ 18b9e6f2a8c5a9518e588f59c2ba16ef7ef9d551; hard_swish micro-model; date 2026-08-10; cmd: (cd tools/tflm-goldens && make TFLM_ROOT=/tmp/tflite-micro run > generated/harness_output.txt)\";\n\n"
        );

        buf.push_str(
            "pub const INPUT_SHAPE: [i32; 4] = [1, 1, 1, 8];\n\
             pub const OUTPUT_SHAPE: [i32; 4] = [1, 1, 1, 8];\n\n"
        );

        buf.push_str(
            "pub const INPUT_ZERO_POINT: i32 = 0;\n\
             pub const OUTPUT_ZERO_POINT: i32 = 0;\n\n\
             pub const INPUT_SCALE: f64 = 1.0;\n\
             pub const OUTPUT_SCALE: f64 = 1.0;\n\n"
        );

        buf.push_str("// HardSwish: x * ReLU6(x+3) / 6 (executed TFLM HardSwishParams chain)\n\n");

        emit_const_array(&mut buf, "INPUT_DATA", "i8", input_data);
        emit_const_array(&mut buf, "EXPECTED_OUTPUT", "i8", expected_output);

        let path = self.output_dir.join("hard_swish.rs");
        std::fs::write(&path, buf).expect("write hard_swish fixture");
        println!("  Wrote {}", path.display());
    }
}

pub fn emit_const_array<T: std::fmt::Display>(buf: &mut String, name: &str, ty: &str, data: &[T]) {
    let _ = writeln!(buf, "pub const {}: [{}; {}] = [", name, ty, data.len());
    for chunk in data.chunks(16) {
        let _ = write!(buf, "    ");
        for (i, val) in chunk.iter().enumerate() {
            if i > 0 {
                let _ = write!(buf, ", ");
            }
            let _ = write!(buf, "{val}");
        }
        let _ = writeln!(buf, ",");
    }
    let _ = writeln!(buf, "];\n");
}
